# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [9]:
import numpy as np
arr = np.load("final.npy")
arr

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 4.000e+00, 7.000e+00,
        0.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 4.100e+00, 7.000e+00,
        0.000e+00],
       [2.000e+00, 0.000e+00, 0.000e+00, ..., 4.400e+00, 7.000e+00,
        0.000e+00],
       ...,
       [6.571e+03, 4.000e+00, 0.000e+00, ..., 4.800e+00, 2.000e+00,
        0.000e+00],
       [6.572e+03, 3.000e+00, 0.000e+00, ..., 5.200e+00, 2.000e+00,
        0.000e+00],
       [6.573e+03, 2.000e+00, 0.000e+00, ..., 4.400e+00, 2.000e+00,
        0.000e+00]])

2. Display the mean and the standard deviation for each column.

In [10]:
np.mean(arr,axis = 0)


array([3.28650000e+03, 5.49950198e+03, 0.00000000e+00, 8.86826894e-02,
       0.00000000e+00, 3.84616969e+01, 3.30841796e+01, 2.49830271e+01,
       0.00000000e+00, 1.01451171e+01, 0.00000000e+00, 0.00000000e+00,
       4.46759963e+00, 6.77654396e+00, 0.00000000e+00])

In [11]:
np.std(arr,axis = 0)

array([1.89775031e+03, 3.97651842e+03, 0.00000000e+00, 4.06686207e-01,
       0.00000000e+00, 1.63396498e+00, 6.28004726e+00, 2.77566002e+01,
       0.00000000e+00, 1.27978334e+01, 0.00000000e+00, 0.00000000e+00,
       4.85681616e-01, 5.41160601e+00, 0.00000000e+00])

3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [20]:
arr[:]-=1
arr[:]-=25
arr[:]-=25
arr[:]-=10
arr[:]-=4

arr

array([[-195. , -195. , -195. , ..., -191. , -188. , -195. ],
       [-194. , -195. , -195. , ..., -190.9, -188. , -195. ],
       [-193. , -195. , -195. , ..., -190.6, -188. , -195. ],
       ...,
       [6376. , -191. , -195. , ..., -190.2, -193. , -195. ],
       [6377. , -192. , -195. , ..., -189.8, -193. , -195. ],
       [6378. , -193. , -195. , ..., -190.6, -193. , -195. ]])

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [22]:
arr[:]*=2

In [23]:
arr

array([[ -390. ,  -390. ,  -390. , ...,  -382. ,  -376. ,  -390. ],
       [ -388. ,  -390. ,  -390. , ...,  -381.8,  -376. ,  -390. ],
       [ -386. ,  -390. ,  -390. , ...,  -381.2,  -376. ,  -390. ],
       ...,
       [12752. ,  -382. ,  -390. , ...,  -380.4,  -386. ,  -390. ],
       [12754. ,  -384. ,  -390. , ...,  -379.6,  -386. ,  -390. ],
       [12756. ,  -386. ,  -390. , ...,  -381.2,  -386. ,  -390. ]])