# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [38]:
import numpy as np
arr = np.load("final.npy")
arr


array([[ 0.    , 36.8578, 44.4161, 16.97  ,  4.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

2. Display the mean and the standard deviation for each column.

In [39]:
np.mean(arr,axis = 0)


array([ 0.     , 37.20543, 33.27595, 19.818  ,  4.38   ])

In [40]:
np.std(arr,axis = 0)

array([ 0.        ,  0.92015317,  6.07459305, 18.28870351,  0.33105891])

3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [41]:
arr[:0]-=1
arr[:1]-=25
arr[:2]-=25
arr[:3]-=10
arr[:4]-=4

arr

array([[-64.    , -27.1422, -19.5839, -47.03  , -60.    ],
       [-39.    ,  -1.5659,  -3.148 , -31.98  , -34.9   ],
       [-14.    ,  23.6878,  23.4016,  -3.73  ,  -9.6   ],
       [ -4.    ,  33.2003,  26.4376,  74.07  ,   0.    ],
       [  0.    ,  35.6846,  26.7266,  42.77  ,   4.5   ],
       [  0.    ,  36.4171,  28.6991,  14.86  ,   4.1   ],
       [  0.    ,  36.0535,  31.2135,  36.68  ,   5.2   ],
       [  0.    ,  37.1958,  30.6241,  50.33  ,   4.8   ],
       [  0.    ,  36.9653,  27.7633,   6.93  ,   4.3   ],
       [  0.    ,  38.893 ,  26.4483,  11.62  ,   4.2   ],
       [  0.    ,  37.3773,  36.3855,  10.53  ,   4.8   ],
       [  0.    ,  35.8861,  26.0695,  28.49  ,   4.9   ],
       [  0.    ,  37.4635,  36.3113,  15.29  ,   4.3   ],
       [  0.    ,  37.0201,  36.0845,  10.    ,   4.1   ],
       [  0.    ,  37.6546,  26.6698,   4.5   ,   4.5   ],
       [  0.    ,  37.5318,  29.848 ,  17.58  ,   4.6   ],
       [  0.    ,  39.0388,  44.1533,   7.52  ,   4.5   

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [42]:
arr[:]*=2

In [43]:
arr

array([[-128.    ,  -54.2844,  -39.1678,  -94.06  , -120.    ],
       [ -78.    ,   -3.1318,   -6.296 ,  -63.96  ,  -69.8   ],
       [ -28.    ,   47.3756,   46.8032,   -7.46  ,  -19.2   ],
       [  -8.    ,   66.4006,   52.8752,  148.14  ,    0.    ],
       [   0.    ,   71.3692,   53.4532,   85.54  ,    9.    ],
       [   0.    ,   72.8342,   57.3982,   29.72  ,    8.2   ],
       [   0.    ,   72.107 ,   62.427 ,   73.36  ,   10.4   ],
       [   0.    ,   74.3916,   61.2482,  100.66  ,    9.6   ],
       [   0.    ,   73.9306,   55.5266,   13.86  ,    8.6   ],
       [   0.    ,   77.786 ,   52.8966,   23.24  ,    8.4   ],
       [   0.    ,   74.7546,   72.771 ,   21.06  ,    9.6   ],
       [   0.    ,   71.7722,   52.139 ,   56.98  ,    9.8   ],
       [   0.    ,   74.927 ,   72.6226,   30.58  ,    8.6   ],
       [   0.    ,   74.0402,   72.169 ,   20.    ,    8.2   ],
       [   0.    ,   75.3092,   53.3396,    9.    ,    9.    ],
       [   0.    ,   75.0636,   59.696 ,