# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [37]:
import numpy as np
squaremeter=np.array([[56,78,88,99,45,56,76,78,120,140]])
rooms=np.array([[2,4,5,4,5,3,2,2,3,4]])
price=np.array([[100000,50000,60000,50000,120000,780000,60000,70000,70000,120000]])

data=np.concatenate((squaremeter, rooms))
data=np.concatenate((data, price))

data

array([[    56,     78,     88,     99,     45,     56,     76,     78,
           120,    140],
       [     2,      4,      5,      4,      5,      3,      2,      2,
             3,      4],
       [100000,  50000,  60000,  50000, 120000, 780000,  60000,  70000,
         70000, 120000]])

2. Transpose the array you have created, so that every line can represent features of one house.

In [41]:
house_new = data.transpose()
house_new_2 = data.T

print(data.shape)
print(house_new)


(3, 10)
[[    56      2 100000]
 [    78      4  50000]
 [    88      5  60000]
 [    99      4  50000]
 [    45      5 120000]
 [    56      3 780000]
 [    76      2  60000]
 [    78      2  70000]
 [   120      3  70000]
 [   140      4 120000]]


3. Display the shape of the array and explain what it means.

In [43]:
house_new.shape

(10, 3)

10 means rows 
3 means columns


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [21]:
import numpy as np

def create_array(x,y):
    arr=np.ones((x, y))
    for i in range(1,x,2):
        for j in range(1,y,2):
            arr[i,j]=0
    return arr
create_array(6,5)


array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])